# Generated by Django 3.1.1 on 2020-10-13 05:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201013_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profile', verbose_name=django.contrib.auth.models.User),
        ),
    ]
